HALF_SQUARE_WIDTH = 30
SQUARE_WIDTH = HALF_SQUARE_WIDTH * 2
INTERNAL_SQUARE_WIDTH = 15
INTERNAL_SQUARE_HEIGHT = 15
HALF_SQUARE_HEIGHT = 30
SQUARE_HEIGHT = HALF_SQUARE_HEIGHT * 2
SPACER = 1
SQUARE_SPACING = int(SQUARE_WIDTH + SPACER)
INTERNAL_SQUARE_SPACING = int(INTERNAL_SQUARE_WIDTH + SPACER)
TOTAL_WIDTH_SPACING = int(HALF_SQUARE_WIDTH*2+(SQUARE_SPACING//2))
TOTAL_HEIGHT_SPACING = int(HALF_SQUARE_HEIGHT*2+(SQUARE_SPACING//2))

# Set how many rows and columns we will have
# ROW_COUNT = 5
# COLUMN_COUNT = 13
# ROW_COUNT = 15
# COLUMN_COUNT = 15
# ROW_COUNT = 11
# COLUMN_COUNT = 15

# ROW_COUNT = 6
# COLUMN_COUNT = 8

ROW_COUNT = 9
COLUMN_COUNT = 9

# ROW_COUNT = 4
# COLUMN_COUNT = 4
#
# ROW_COUNT = 7
# COLUMN_COUNT = 11

# ROW_COUNT = 13
# COLUMN_COUNT = 25

SIDE_BAR_WIDTH = 400

SCREEN_WIDTH = SQUARE_SPACING*COLUMN_COUNT-SPACER
SCREEN_WIDTH_W_BAR = SCREEN_WIDTH + SIDE_BAR_WIDTH
SCREEN_HEIGHT = SQUARE_SPACING*ROW_COUNT-SPACER

# This sets the WIDTH and HEIGHT of each grid location
WIDTH = 1
HEIGHT = 1

# This sets the margin between each cell
# and on the edges o f the screen.
MARGIN = 1

MOVEMENT_SPEED = 1
MAX_SPEED = 1
MIN_SPEED = -1
# STARTX = COLUMN_COUNT//2
# STARTY = ROW_COUNT//2

# Badger's default spawn: LEFT edge, vertically centred. NB the names are historically swapped --
# Simple_Agent(STARTX, STARTY, ...) takes (column, row), so STARTX is a COLUMN and STARTY a ROW.
STARTX = 0                    # left-hand column
STARTY = ROW_COUNT // 2       # same height (middle row)

MAX_TIME = 100

# STARTSQUAREX = (SQUARE_SPACING * STARTX + SQUARE_SPACING // 2)
# STARTSQUAREY = (SQUARE_SPACING * STARTY + SQUARE_SPACING // 2)

STARTSQUAREX = (SQUARE_SPACING * STARTX + SQUARE_SPACING // 2)
STARTSQUAREY = (SQUARE_SPACING * STARTY + SQUARE_SPACING // 2)

# STARTSQUAREX = (SQUARE_SPACING * STARTX + SQUARE_SPACING // 2)
# STARTSQUAREY = (SQUARE_SPACING * STARTY + SQUARE_SPACING // 2)

# screen dimensions
# SCREEN_WIDTH = (WIDTH + MARGIN) * COLUMN_COUNT + MARGIN
# SCREEN_HEIGHT = (HEIGHT + MARGIN) * ROW_COUNT + MARGIN
